name: gg_project_root
description: Returns the dart project root for a given folder by looking for pubspec_yaml.dart
version: 1.0.4
repository: https://github.com/inlavigo/gg_project_root.git

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  args: ^2.4.2
  colorize: ^3.0.0
  gg_args: ^2.0.1
  gg_log: ^1.0.0
  gg_process: ^1.0.1
  path: ^1.8.0

dev_dependencies:
  gg_capture_print: ^1.0.2
  gg_install_gg: ^1.0.1
  lints: ^3.0.0
  pana: ^0.22.2
  test: ^1.24.0