// @license
// Copyright (c) ggsuite
//
// Use of this source code is governed by terms that can be
// found in the LICENSE file in the root of this package.

// GENERATED BY gg_version WriteVersionFile - DO NOT EDIT.
// Kept in sync by test/gg_project_root_version_test.dart.
// coverage:ignore-file

/// The version of the `gg_project_root` package.
const String ggProjectRootVersion = '2.0.1';
